language: php

php:
  - 7.0.30

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - docker pull php:7.2-apache
  - docker pull italia/spid-testenv2

install:
  - composer install --no-interaction
  - docker --version
  - docker-compose --version
  - docker-compose -f tests/docker-compose-travis.yml pull
  - docker-compose -f tests/docker-compose-travis.yml up --build --no-start
  - docker-compose -f tests/docker-compose-travis.yml start
  - docker ps

before_script:
  - source .env
  - wget --spider --timeout=15 --retry-connrefused "$SP_ENTITYID"
  - wget --spider --timeout=15 --retry-connrefused "$IDP_ENTITYID"
